---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/lidarr
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/lidarr/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/lidarr/music:/music #optional
      - CHANGE_TO_COMPOSE_DATA_PATH/lidarr/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
