---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/znc
services:
  znc:
    image: lscr.io/linuxserver/znc:latest
    container_name: znc
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/znc/Config:/config
    ports:
      - 6501:6501
    restart: unless-stopped
