---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/libreoffice
services:
  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    container_name: libreoffice
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/libreoffice/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
