---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/netbootxyz
# https://hub.docker.com/r/netbootxyz/netbootxyz
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - MENU_VERSION=1.9.9 #optional
      - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
      - NGINX_PORT=80 #optional
      - WEB_APP_PORT=3000 #optional
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/netbootxyz/config:/config # optional
      - CHANGE_TO_COMPOSE_DATA_PATH/netbootxyz/assets:/assets # optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80 #optional
    restart: unless-stopped
