services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/Config/netbootxyz/config:/config # optional
      - CHANGE_TO_COMPOSE_DATA_PATH/Config/netbootxyz/assets:/assets # optional
    ports:
      - 3300:3000
      - 369:69/udp
      - 38080:80 #optional
    restart: unless-stopped
