---
# Date: 2025-06-01
# https://hub.docker.com/_/php/
services:
  php-apache:
    image: php:8.2-apache
    container_name: php-webserver
    working_dir: /var/www/html
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/php-webserver/html:/var/www/html
    ports:
      - "8085:80"
