---
# Date: 2025-06-01
# https://github.com/benbusby/whoogle-search
services:
  whoogle:
    image: benbusby/whoogle-search:latest
    container_name: whoogle
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/whoogle:/config
    ports:
      - 5000:5000
    restart: unless-stopped
