version: '3.8'
services:
  db:
    image: postgres:${TAG}
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '5432:5432'
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
