---
# Date: 2025-06-01
# https://github.com/gotson/komga
# https://komga.org/docs/introduction
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/komga/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/komga/comic:/data
      - CHANGE_TO_COMPOSE_DATA_PATH/homga/tmp:/tmp
    ports:
      - 25600:25600
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
    restart: unless-stopped
