---
networks:
  my-net:
    external: true
services:
  komga:
    image: gotson/komga
    container_name: komga
    networks:
      my-net:
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/komga/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/komga/comic:/data
      - CHANGE_TO_COMPOSE_DATA_PATH/homga/tmp:/tmp
    ports:
      - 88:8080
    user: "$PUID:$PGID"
    environment:
      - TZ=$TZ
    restart: unless-stopped
