---
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - PUID=1000
      - GUID=1000
    ports:
      - "8080:80"
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/srv:/srv # files will be stored here
      - CHANGE_TO_COMPOSE_DATA_PATH/appdata/filebrowser/filebrowser.db:/database/database.db # users info/settings will be stored here
      - CHANGE_TO_COMPOSE_DATA_PATH/appdata/filebrowser/filebrowser.json:/config/filebrowser.json # config file
    restart: always
