---
# Date: 2025-06-01
# https://docs.linuxserver.io/images/docker-freshrss/
# https://hub.docker.com/r/freshrss/freshrss
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - CHANGE_TO_COMPOSE_DATA_PATH/freshrss:/config
    ports:
      - 9080:80
    restart: unless-stopped
