---
version: "2.1"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1001
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/docker/docker-config/freshrss:/config
    ports:
      - 9080:80
    restart: unless-stopped
