---
# https://hub.docker.com/r/linuxserver/nzbhydra2
services:
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/nzbhydra2/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/nzbhydra2/downloads:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped
