---
# https://hub.docker.com/r/linuxserver/nzbhydra2
version: "2.1"
services:
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/data:/config
      - /nzb/download:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped
