---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:amd64-latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
      - CHANGE_TO_COMPOSE_DATA_PATH/sonarr/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/sonarr/downloads:/downloads
      - CHANGE_TO_COMPOSE_DATA_PATH/sonarr/tv-series:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
