---
# https://github.com/linuxserver/docker-wikijs
services:
  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: wikijs
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - DB_TYPE=sqlite #optional
      - DB_HOST= #optional
      - DB_PORT= #optional
      - DB_NAME= #optional
      - DB_USER= #optional
      - DB_PASS= #optional
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/wikijs/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/wikijs/data:/data
    ports:
      - 3000:3000
    restart: unless-stopped
