---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/overseerr
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
