---
# Date: 2025-06-01
# https://dashy.to/
# https://github.com/Lissy93/dashy
services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: dashy
    # conf.yml on host must exist prior to uncommenting the volumes line and data mapping line
    # basic conf.yml can be found at https://github.com/Lissy93/dashy
    # volumes:
    #  - ${PATH_TO_DATA}/dashy/conf.yml:/app/user-data/conf.yml
    ports:
      - 4000:8080
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
