---
# Date: 2025-06-1
# https://hub.docker.com/r/adguard/adguardhome
# https://github.com/AdguardTeam/AdGuardHome
# Note: 192.168.1.xxx is an example network, you must update all these to match your own.
networks:
  MyMacVlan:
    external: true
services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    cap_add:
      - NET_ADMIN
    networks:
      MyMacVlan: # <-- MACVlan Name You need to create first in Portainer WebGUI.
        ipv4_address: 192.168.1.3 # <-- Update to your desired Pihole IPv4
        # https://www.youtube.com/watch?v=4741-YR31fM
        # https://www.youtube.com/watch?v=o7nn6Tv-PAw
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/adguard/work:/opt/adguardhome/work
      - CHANGE_TO_COMPOSE_DATA_PATH/adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped
