---
# https://github.com/jlesage/docker-handbrake
services:
  handbrake:
    image: jlesage/handbrake
    ports:
      - "5800:5800"
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/handbrake/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/handbrake/storage:/storage:ro
      - CHANGE_TO_COMPOSE_DATA_PATH/handbrake/watch:/watch
      - CHANGE_TO_COMPOSE_DATA_PATH/handbrake/output:/output
