---
# https://github.com/daledavies/jump
services:
  web:
    image: daledavies/jump
    container_name: jump
    ports:
      - 8123:8080
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/jump/backgrounds:/backgrounds
      - CHANGE_TO_COMPOSE_DATA_PATH/jump/favicon:/favicon
      - CHANGE_TO_COMPOSE_DATA_PATH/jump/search:/search
      - CHANGE_TO_COMPOSE_DATA_PATH/jump/sites:/sites
    environment:
      SITENAME: 'Custom site name'
      OWMAPIKEY: '0a1b2c3d4e5f6a7b8c9d0a1b'
      LATLONG: '51.509865,-0.118092'
    restart: unless-stopped
