services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
    ports:
      - "19132:19132/udp"
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/data:/data
    stdin_open: true
    tty: true 
