---
# Date: 2025-06-01
# https://github.com/itzg/docker-minecraft-bedrock-server
services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
    ports:
      - "19132:19132/udp"
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/minecraft-bedrock-server:/data
    stdin_open: true
    tty: true
