---
# Date: 2025-06-01
# https://hub.docker.com/r/lmscommunity/lyrionmusicserver
# https://lyrion.org/getting-started/beginners-guide-omv-docker/
services:
  lms:
    container_name: lms
    image: lmscommunity/lyrionmusicserver
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/lms/config:/config:rw
      - CHANGE_TO_COMPOSE_DATA_PATH/lms/music:/music:ro
      - CHANGE_TO_COMPOSE_DATA_PATH/lms/playlist:/playlist:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9000:9000/tcp
      - 9090:9090/tcp
      - 3483:3483/tcp
      - 3483:3483/udp
    environment:
      - HTTP_PORT=9000
    restart: always
