---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/wireshark
services:
  Wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/wireshark/config:/config
    ports:
      - 3000:3000
    restart: unless-stopped
