---
# Date: 2025-06-01
# https://github.com/dockur/macos
# see github page for many more options and macos versions 
services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "13"
      #DISK_SIZE: "256G"
      #RAM_SIZE: "8G"
      #CPU_CORES: "4"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/macos:/storage
    restart: always
    stop_grace_period: 2m
