---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/transmission
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/transmission/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/transmission/downloads:/downloads
      - CHANGE_TO_COMPOSE_DATA_PATH/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
