---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/smokeping
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1001
      - PGID=100
      - TZ=America/New_York
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/smokeping/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/smokeping/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
    restart: unless-stopped
