---
# Date: 2025-06-01
# https://hub.docker.com/r/jlesage/makemkv
# https://github.com/jlesage/docker-makemkv
services:
  makemkv:
    image: jlesage/makemkv
    container_name: makemkv
    ports:
      - '5800:5800'
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/makemkv/config:/config:rw
      - CHANGE_TO_COMPOSE_DATA_PATH/makemkv/storage:/storage:ro
      - CHANGE_TO_COMPOSE_DATA_PATH/makemkv/output:/output:rw
    devices:
      - /dev/sr0
      - /dev/sr1
    restart: unless-stopped
