services:
  utorrent:
    image: ekho/utorrent:latest
    volumes:
      - utorrent-settings:/utorrent/settings
      - CHANGE_TO_COMPOSE_DATA_PATH/torrent:/downloads
    environment:
      UID: 1000
      GID: 1000
      webui: ng # NG OR UT
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  utorrent-settings:
