---
# https://hub.docker.com/r/linuxserver/sabnzbd
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/sabnzbd/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/sabnzbd/downloads:/downloads #optional
      - CHANGE_TO_COMPOSE_DATA_PATH/sabnzbd/incomplete:/incomplete-downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
