---
# https://github.com/louislam/uptime-kuma
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/uptime-kuma/data:/app/data
    ports:
      - 3001:3001 # Host Port:Container Port
    restart: unless-stopped
