---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/dokuwiki
services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/dokuwiki/config:/config
    ports:
      - 80:80
      - 443:443 #optional
    restart: unless-stopped
