---
services:
  airsonic:
    image: linuxserver/airsonic:latest
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=100
      - CONTEXT_PATH=airsonic
      - JAVA_OPTS='-Xms256m -Xmx512m'
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/Music:/music
      - CHANGE_TO_COMPOSE_DATA_PATH/appdata/Airsonic/Playlists:/playlists
      - CHANGE_TO_COMPOSE_DATA_PATH/Podcasts:/podcasts
      - CHANGE_TO_COMPOSE_DATA_PATH/appdata/Airsonic/Media:/media
      - CHANGE_TO_COMPOSE_DATA_PATH/appdata/Config/Airsonic:/config
    ports:
      - 4040:4040
    restart: unless-stopped
