---
# Date: 2025-06-01
# https://github.com/jlesage/docker-mediainfo
# https://mediaarea.net/en/MediaInfo
services:
  mediainfo:
    image: jlesage/mediainfo
    ports:
      - "5800:5800"
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/mediainfo/config:/config:rw
      - CHANGE_TO_COMPOSE_DATA_PATH/mediainfo/storage:/storage:ro
