---
# https://github.com/jlesage/docker-mediainfo
services:
  mediainfo:
    image: jlesage/mediainfo
    ports:
      - "5800:5800"
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/mediainfo/config:/config:rw
      - CHANGE_TO_COMPOSE_DATA_PATH/mediainfo/storage:/storage:ro
