---
services:
  Yaak:
    image: linuxserver/yaak:latest
    container_name: Yaak
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/appdata/yaak/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
