# Date: 2025-06-01
# https://hub.docker.com/r/thingsboard/tb-postgres
services:
  mytb:
    restart: always
    image: thingsboard/tb-postgres:latest
    ports:
      - 8080:9090
      - 1883:1883
      - 7070:7070
      - 5683-5688:5683-5688/udp
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/thingsboard/mytb-data:/data
      - CHANGE_TO_COMPOSE_DATA_PATH/thingsboard/mytb-logs:/var/log/thingsboard
