---
# Date: 2025-06-01
# https://github.com/henrygd/beszel
# https://beszel.dev/
services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    ports:
      - 8090:8090
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/beszel:/beszel_data
