services:
  emby:
    image: emby/embyserver
    container_name: embyserver
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/appdata/embyserver:/config # Configuration directory
      - CHANGE_TO_COMPOSE_DATA_PATH/appdata/tvshows:/mnt/share1 # Media directory
      - CHANGE_TO_COMPOSE_DATA_PATH/appdata/movies:/mnt/share2 # Media directory
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    restart: on-failure
