---
services:
  ldap:
    image: osixia/openldap:latest
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "home"
      LDAP_DOMAIN: "domain.com"
      LDAP_ADMIN_PASSWORD: "adminpassword"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/ldap/ldap_data:/var/lib/ldap
      - CHANGE_TO_COMPOSE_DATA_PATH/ldap/ldap_config:/etc/ldap/slapd.d
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    ports:
      - "6443:443"
    depends_on:
      - ldap
