---
# Date: 2025-06-01
# https://github.com/gotify/server
# https://gotify.net/docs/
services:
  gotify:
    image: gotify/server
    ports:
      - 8080:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS: 'admin' #default user is admin
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/gotify:/app/data
