---
# Date: 2025-06-01
#https://hub.docker.com/r/linuxserver/prowlarr
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
