---
# https://hub.docker.com/r/linuxserver/deluge
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/deluge/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
