---
services:
  Wps-office:
    image: linuxserver/wps-office:latest
    container_name: Wps-office
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/appdata/wps-office/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
