---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/wps-office
services:
  Wps-office:
    image: lscr.io/linuxserver/wps-office:latest
    container_name: Wps-office
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/wps-office/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
