---
# https://hub.docker.com/r/fallenbagel/jellyseerr
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tashkent
    ports:
      - 5055:5055
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/jellyseerr:/app/config
    restart: unless-stopped
