---
# Date: 2025-06-01
# https://github.com/xwiki/xwiki-docker
networks:
  bridge:
    driver: bridge
services:
  web:
    image: "xwiki:stable-postgres-tomcat"
    container_name: xwiki-postgres-tomcat-web
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_HOST=xwiki-postgres-db
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/xwiki/data:/usr/local/xwiki
    networks:
      - bridge
  db:
    image: "postgres:17"
    container_name: xwiki-postgres-db
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/xwiki/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_ROOT_PASSWORD=xwiki
      - POSTGRES_PASSWORD=xwiki
      - POSTGRES_USER=xwiki
      - POSTGRES_DB=xwiki
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    networks:
      - bridge
