---
# Date: 2025-06-01
# https://hub.docker.com/r/b4bz/homer
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/homer:/www/assets
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=100
    restart: unless-stopped
