---
# https://hub.docker.com/r/vladgh/minidlna/
# https://github.com/vladgh/docker_base_images/tree/main/minidlna
version: '3'
services:
  dlna:
    image: vladgh/minidlna:latest
    container_name: minidlna
    restart: unless-stopped
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/minidlna/audio:/media/audio
      - CHANGE_TO_COMPOSE_DATA_PATH/minidlna/video:/media/video
    environment:
      - MINIDLNA_MEDIA_DIR_1=/media/audio
      - MINIDLNA_MEDIA_DIR_2=/media/video
      - MINIDLNA_FRIENDLY_NAME=omvdlna
      - PUID=1001
      - PGID=100
    network_mode: "host"
