---
# https://github.com/SelfhostedPro/Yacht
version: "3"
services:
  yacht:
    container_name: yacht
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    image: selfhostedpro/yacht
volumes:
  yacht:
