---
# Date: 2025-06-01
# https://github.com/wizarrrr/wizarr
services:
  wizarr:
    image: ghcr.io/wizarrrr/wizarr
    container_name: wizarr
    environment:
      - APP_URL=https://wizarr.domain.com
      - DISABLE_BUILTIN_AUTH=false #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - TZ=Europe/London #Set your timezone here
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/wizarr/db:/data/database
      - CHANGE_TO_COMPOSE_DATA_PATH/wizarr/wizard:/data/wizard_steps
    ports:
      - 5690:5960
    restart: unless-stopped
