---
services:
  clamav:
    image: mkodockx/docker-clamav:alpine
    container_name: clamav
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - CHANGE_TO_COMPOSE_DATA_PATH/clamav/config:/etc/clamav
      - CHANGE_TO_COMPOSE_DATA_PATH/clamav/virus_definitions:/var/lib/clamav
    ports:
      - 3310:3310
    restart: unless-stopped
