---
# Date: 2025-06-01
# https://hub.docker.com/r/dperson/torproxy
services:
  torproxy:
    image: dperson/torproxy
    container_name: torproxy
    ports:
      - 8118:8118
      - 9050:9050
    environment:
      - TZ=America/New_York
    restart: unless-stopped
