---
# Date: 2025-06-01
# https://hub.docker.com/r/uroni/urbackup-server
services:
  urbackup:
    image: uroni/urbackup-server:latest
    container_name: urbackup
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/urbackup/db:/var/urbackup
      - CHANGE_TO_COMPOSE_DATA_PATH/urbackup/backups:/backups
    network_mode: "host"
