---
# https://hub.docker.com/r/kizaing/kavita
version: '3.9'
services:
  kavita:
    image: kizaing/kavita:latest
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/kavita/manga:/manga
      - CHANGE_TO_COMPOSE_DATA_PATH/kavita/data:/kavita/config
    ports:
      - "5000:5000"
    restart: unless-stopped
