---
services:
  emulatorjs:
    image: linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Europe/Amsterdam
      - SUBFOLDER=/
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/appdata/emulatorjs/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/appdata/emulatorjs/data:/data
    ports:
      - 3000:3000
      - 80:80
      - 4001:4001
    restart: unless-stopped
