---
# Date: 2025-06-01
# https://docs.linuxserver.io/images/docker-emulatorjs/
services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Amsterdam
      - SUBFOLDER=/ #optional
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/emulatorjs/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/emulatorjs/data:/data
    ports:
      - 3000:3000
      - 80:80
      - 4001:4001
    restart: unless-stopped
