---
# https://hub.docker.com/r/linuxserver/bookstack
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://bookstack.example.com
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=YOUR_DB_PASSWORD
      - DB_DATABASE=bookstackapp
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/bookstack/app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=YOUR_DB_ROOT_PASSWORD
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=YOUR_DB_PASSWORD
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/bookstack/db_data:/config
    restart: unless-stopped
