---
services:
  bitwardenrs:
    image: bitwardenrs/server:latest
    container_name: bitwardenrs
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/appdata/Config/Bitwarden-rs:/config
    ports:
      - 80:80
    restart: unless-stopped
