---
# https://hub.docker.com/r/josh5/unmanic
services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    environment:
      - PUID=1001
      - PGID=100
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/unmanic/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/unmanic/library:/library
      - CHANGE_TO_COMPOSE_DATA_PATH/unmanic/encode_cache:/tmp/unmanic
