---
# Date: 2025-06-01
# https://docs.linuxserver.io/images/docker-bambustudio/
# https://hub.docker.com/r/linuxserver/bambustudio
services:
  bambustudio:
    image: linuxserver/bambustudio:latest
    container_name: bambustudio
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Amsterdam
      - DARK_MODE=true
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/bambustudio/config:/config
    ports:
      - 3000:3000/tcp
      - 3001:3001/tcp
    restart: unless-stopped
