---
# Date: 2025-06-01
# https://github.com/advplyr/audiobookshelf
# https://hub.docker.com/r/advplyr/audiobookshelf
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf
    container_name: audiobookshelf
    ports:
      - 13378:80 #do not change :80
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/audiobookshelf/podcasts:/podcasts
      - CHANGE_TO_COMPOSE_DATA_PATH/audiobookshelf/metadata:/metadata
      - CHANGE_TO_COMPOSE_DATA_PATH/audiobookshelf/config:/config
    restart: unless-stopped
