---
# Date: 2025-06-01
# https://github.com/favonia/cloudflare-ddns
services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    # Choose the appropriate tag based on your need:
    # - "latest" for the latest stable version (which could become 2.x.y
    #   in the future and break things)
    # - "1" for the latest stable version whose major version is 1
    # - "1.x.y" to pin the specific version 1.x.y
    network_mode: host
    # This bypasses network isolation and makes IPv6 easier (optional; see below)
    restart: always
    # Restart the updater after reboot
    user: "1000:100"
    # Run the updater with specific user and group IDs (in that order).
    # You can change the two numbers based on your need.
    read_only: true
    # Make the container filesystem read-only (optional but recommended)
    cap_drop: [all]
    # Drop all Linux capabilities (optional but recommended)
    security_opt: ['no-new-privileges:true']
    # Another protection to restrict superuser privileges (optional but recommended)
    environment:
      - CLOUDFLARE_API_TOKEN=YOUR-CLOUDFLARE-API-TOKEN
      # Your Cloudflare API token
      - DOMAINS=example.org,www.example.org,example.io
      # Your domains (separated by commas)
      - PROXIED=true
      # Tell Cloudflare to cache webpages and hide your IP (optional)
    #networks:
    #  LAN0:
    #    external: true
    #    name: LAN0
    # Introduce custom Docker networks to the 'services' in this file. A common use case
    # for this is binding one of the 'services' to a specific network interface available at
    # Docker's host. This section is required for the 'networks' section of each 'services'.
