---
# Date: 2025-06-01
# https://docs.gitlab.com/install/docker/installation/#install-gitlab-by-using-docker-compose
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.example.com'
    ports:
      - '80:80' # HTTP
      - '443:443' # HTTPS
      - '22:22' # SSH
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/gitlab/config:/etc/gitlab
      - CHANGE_TO_COMPOSE_DATA_PATH/gitlab/logs:/var/log/gitlab
      - CHANGE_TO_COMPOSE_DATA_PATH/gitlab/data:/var/opt/gitlab
    shm_size: '256m'
