services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['initial_root_password'] = 'SET ROOT PASSWORD'
    ports:
      - '8929:8929' #HTTP
      - '443:443' #HTTPS
      - '2424:22' #SSH ?
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/gitlab/config:/etc/gitlab
      - CHANGE_TO_COMPOSE_DATA_PATH/gitlab/logs:/var/log/gitlab
      - CHANGE_TO_COMPOSE_DATA_PATH/gitlab/data:/var/opt/gitlab
    shm_size: '256m'
