---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/thelounge
services:
  thelounge:
    image: lscr.io/linuxserver/thelounge:latest
    container_name: thelounge
    ports:
      - 9000:9000:tcp
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/thelounge:/config
