---
# Date: 2025-06-01
# https://github.com/open-webui/open-webui
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    ports:
      - 3013:8080
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/webui/ollama:/root/.ollama
      - CHANGE_TO_COMPOSE_DATA_PATH/webui/open-webui:/app/backend/data
    container_name: open-webui
    restart: unless-stopped
