---
services:
  node-red:
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    networks:
      - node-red-net
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/node-red/data:/data
networks:
  node-red-net:
