---
# Date: 2025-09-13
# https://github.com/arabcoders/ytptube

services:
  ytptube:
    user: $UID:${GID-$UID}
    image: ghcr.io/arabcoders/ytptube:latest
    container_name: ytptube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./config:/config:rw
      - ./downloads:/downloads:rw
    tmpfs:
      - /tmp
