---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/plex
# https://github.com/plexinc/pms-docker
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /dev/shm:/transcode
      - /etc/localtime:/etc/localtime:ro
      - CHANGE_TO_COMPOSE_DATA_PATH/plex/database:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/plex/multimedia:/multimedia
    restart: unless-stopped
