---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=100
      - VERSION=latest
    volumes:
      - /dev/shm:/transcode
      - /etc/localtime:/etc/localtime:ro
      - CHANGE_TO_COMPOSE_DATA_PATH/plex/database:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/plex/multimedia:/multimedia
    restart: unless-stopped
