---
# https://recyclarr.dev/wiki/installation/
services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    init: true
    user: 1000:1000
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/recyclarr:/config
    environment:
      - TZ=Europe/London
