---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/code-server
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/code-server/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
