---
# Date 2025-06-01
# https://docs.linuxserver.io/images/docker-bazarr
# https://hub.docker.com/r/linuxserver/bazarr
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/bazarr/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/bazarr/movies:/movies #optional
      - CHANGE_TO_COMPOSE_DATA_PATH/bazarr/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
