---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/blender
services:
  blender:
    image: lscr.io/linuxserver/blender:latest
    container_name: blender
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/blender/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
