---
services:
  blender:
    image: linuxserver/blender:latest
    container_name: blender
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Europe/Amsterdam
      - SUBFOLDER=/
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/appdata/blender/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
