---
networks:
  gitea:
    external: false
services:
  server:
    image: codeberg.org/forgejo/forgejo:10.0.0
    container_name: gitea
    environment:
      - USER_UID=1001
      - USER_GID=100
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=dbname
      - GITEA__database__USER=dbuser
      - GITEA__database__PASSWD=dbpass
      - ROOT_URL=http://some.domain.com:3000/
    restart: always
    networks:
      - gitea
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=dbname
    networks:
      - gitea
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/gitea/mysql:/var/lib/mysql
