---
# Date: 2025-10-22
# https://codeberg.org/forgejo/forgejo
networks:
  forgejo:
    external: false
services:
  server:
    image: codeberg.org/forgejo/forgejo:13
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=100
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=dbname
      - GITEA__database__USER=dbuser
      - GITEA__database__PASSWD=dbpass
      - ROOT_URL=http://some.domain.com:3000/
    restart: always
    networks:
      - forgejo
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/forgejo/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=dbname
    networks:
      - forgejo
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/forgejo/mysql:/var/lib/mysql
