---
# https://hub.docker.com/r/linuxserver/firefox
services:
  firefox:
    image: lscr.io/linuxserver/firefox
    container_name: firefox
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
    ports:
      - 3000:3000 # http
      #- 3001:3001 # https
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/firefox/config:/config
    shm_size: "1gb"
    restart: unless-stopped
