apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f firefox.yml convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: firefox
  name: firefox
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: firefox
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f firefox.yml convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/firefox-default: "true"
        io.kompose.service: firefox
    spec:
      containers:
        - env:
            - name: PGID
              value: "100"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/Chicago
          image: lscr.io/linuxserver/firefox
          name: firefox
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
            - containerPort: 3001
              hostPort: 3001
              protocol: TCP
      restartPolicy: Always
