---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/duplicati
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - SETTINGS_ENCRYPTION_KEY=
      - CLI_ARGS= #optional
      - DUPLICATI__WEBSERVICE_PASSWORD= #optional
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/duplicati/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/duplicati/backups:/backups
      - CHANGE_TO_COMPOSE_DATA_PATH/duplicati/source:/source
    ports:
      - 8200:8200
    restart: unless-stopped
