---
# Date: 2025-06-01
# https://github.com/butlerx/wetty
# will have to append /wetty to url that compose plugin opens
# change HOST_IP_ADDRESS, USER_NAME, and CONTAINER_NAME
services:
  wetty:
    image: wettyoss/wetty
    ports:
      - '3001:3000'
    command:
      - "--ssh-host=HOST_IP_ADDRESS"
      - "--command"
      - "docker exec -it CONTAINER_NAME /bin/bash"
      - "--ssh-user=USER_NAME"
    entrypoint:
      - "yarn"
      - "start"
